### ISSUE TITLE
Docker部署缺少依赖问题

### ISSUE THREAD

**Issue by marswh12312313** [kexue-z/nonebot-plugin-htmlrender#10]
系统：linux mint

Dockerfile：
    
    FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

    ENV APP_MODULE=bot:app
    ENV MAX_WORKERS=1

    WORKDIR /app

    COPY ./ /app

    COPY ./requirements.txt ./

    RUN python3 -m pip install -r requirements.txt --no-dependencies

    RUN python3 -m playwright install

    RUN python3 -m playwright install-deps

    RUN rm requirements.txt

镜像构建时

    Step 9/10 : RUN python3 -m playwright install-deps
    ……
    E: Package 'ttf-ubuntu-font-family' has no installation candidate
    E: Unable to locate package libenchant1c2a
    E: Unable to locate package libicu66
    E: Package 'libjpeg-turbo8' has no installation candidate

启动时
机器人是启动成功的

╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     playwright install                                                  ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝

╔════════════════════════════════════════════════════════════╗
║ Host system is missing a few dependencies to run browsers. ║
║ Please install them with the following command:            ║
║                                                            ║
║     playwright install-deps                                ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

小白求解

**Comment by kexue-z** [comment]
参考dao-bot 的dockerfile

--------------原始邮件--------------
发件人："marswh12312313 ***@***.***&gt;;
发送时间：2022年2月4日(星期五) 下午4:18
收件人："kexue-z/nonebot-plugin-htmlrender" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[kexue-z/nonebot-plugin-htmlrender] Docker部署缺少依赖问题 (Issue #10)
-----------------------------------

 

 
系统：linux mint
 
Dockerfile：
 FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8
 
ENV APP_MODULE=bot:app
 ENV MAX_WORKERS=1
 
WORKDIR /app
 
COPY ./ /app
 
COPY ./requirements.txt ./
 
RUN python3 -m pip install -r requirements.txt --no-dependencies
 
**RUN python3 -m playwright install
 
RUN python3 -m playwright install-deps**
 
RUN rm requirements.txt
 
镜像构建时
 Step 9/10 : RUN python3 -m playwright install-deps …… E: Package 'ttf-ubuntu-font-family' has no installation candidate E: Unable to locate package libenchant1c2a E: Unable to locate package libicu66 E: Package 'libjpeg-turbo8' has no installation candidate  
启动时
 
╔═════════════════════════════════════════════════════════════════════════╗
 ║ Looks like Playwright Test or Playwright was just installed or updated. ║
 ║ Please run the following command to download new browsers:              ║
 ║                                                                         ║
 ║     playwright install                                                  ║
 ║                                                                         ║
 ║ <3 Playwright Team                                                      ║
 ╚═════════════════════════════════════════════════════════════════════════╝
 
╔════════════════════════════════════════════════════════════╗
 ║ Host system is missing a few dependencies to run browsers. ║
 ║ Please install them with the following command:            ║
 ║                                                            ║
 ║     playwright install-deps                                ║
 ║                                                            ║
 ║ <3 Playwright Team                                         ║
 ╚════════════════════════════════════════════════════════════╝
 
小白求解
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by marswh12312313** [comment]
已经解决。
