### ISSUE TITLE
pm2挂载nonebot2进程卡死

### ISSUE THREAD

**Issue by york-yang-me** [kexue-z/nonebot-plugin-htmlrender#19]
一开始是在树莓派armv8架构下不通过pm2启动bot的，运行正常，没有问题。
但是换用pm2后台运行nonebot2后就发生了与#17 类似的问题，尝试了提到的解决办法，但依旧没有办法解决。
![image](https://user-images.githubusercontent.com/54138717/168477262-d9fe2e07-c032-4f1c-8e93-24e6f5f6eddd.png)
输入日志就一直卡在 Scheduler Started就不往下打log了

**Comment by kexue-z** [comment]
不懂 pm2 但是我知道如果网络不好就会卡住

检查 pm2 运行的环境和你正常运行的环境是否一致，尝试单独运行 playwright 看看

实在不行试试docker吧（

**Comment by york-yang-me** [comment]
虽然不是长远之计，临时这么苟了一下：通过pm2挂载go-cqhttp的进程，然后利用xdrp远程访问树莓派图形化界面，直接在服务器那边开了个终端窗口启nonebot2~

**Comment by kexue-z** [comment]
??? 不懂什么原理 八成是playwright的问题

**Comment by york-yang-me** [comment]
我也怀疑是playwright的原因，刚刚在browser.py的get_browser()方法里直接打logger.info()的时候也是卡在获取playwright变量的地方，不用pm2挂载是能返回信息的，挂了之后就输出不了了

**Comment by kexue-z** [comment]
树莓派对 `chromium` 支持不完善，建议参考 `README` 修改为 `firefox`
