### ISSUE TITLE
所有图像化输出全部超时

### ISSUE THREAD

**Issue by HolyFishhh** [kexue-z/nonebot-plugin-htmlrender#20]
nb插件中需要图像化的都报超时，询问了插件作者也无法有效解决
第一次使用issues，有什么做的不到位的轻喷..
![board1](https://user-images.githubusercontent.com/103620154/169293330-0f748f58-8021-433c-8d5a-c904cf22057f.png)
![board2](https://user-images.githubusercontent.com/103620154/169293340-10b7f393-73c6-4460-bd44-e7cfac8197ea.png)
![ddcheck](https://user-images.githubusercontent.com/103620154/169293348-d693e331-23c9-40fb-a89c-a1ed569ea771.png)
![QQ截图20220519202706](https://user-images.githubusercontent.com/103620154/169293352-84c37c72-8cca-4945-8bc7-14ff099ea9f0.png)
![QQ截图20220519202717](https://user-images.githubusercontent.com/103620154/169293356-d137ed7e-f057-4536-a4ec-9db5a50843b3.png)
![shindan](https://user-images.githubusercontent.com/103620154/169293359-47d7a04e-167f-44c0-880a-a067ebe7d6a3.png)

**Comment by kexue-z** [comment]
推断几点：
- 估计是网页没有载入出来。但是这些html基本都是本地的，所以资源应该没问题
- 也有可能是playwright的内核无响应了，看看内存的占用情况
- 可以自行参考playwright的文档写一个截图的代码，看看是否正常工作
- 如果不行只能更换环境了，建议 docker [试试这个](https://github.com/kexue-z/ubuntu-playwright-cn-python-docker-image ) 内置了我一般用到的东西

**Comment by MeetWq** [comment]
有挂代理吗，有没有可能是代理的原因

**Comment by kexue-z** [comment]
> 有挂代理吗，有没有可能是代理的原因

确实 可能全局代理不通也会这样

**Comment by kexue-z** [comment]
没有提示可能是已经下好了

有没有试过 自己写一段截图的运行一下看看？

如果实在不行只能docker了

**Comment by HolyFishhh** [comment]
> 没有提示可能是已经下好了
> 
> 有没有试过 自己写一段截图的运行一下看看？
> 
> 如果实在不行只能docker了

重装系统解决了，也不知道是哪里出的问题。
谢谢两位佬提供的帮助。

**Comment by HolyFishhh** [comment]
悲报，刚启动没半个小时，再次出现了相同的问题
自己写了个截图方法正常运行，并截图
同时出现了一些新的报错
![QQ图片20220520110916](https://user-images.githubusercontent.com/103620154/169442717-cbf21e0a-3874-401f-82fa-56fa91a12b33.png)
Target page, context or browser has been closed（在logs中显示的，没有截图上）
我该怎么办T T

**Comment by kexue-z** [comment]
我放弃思考了 快使用docker

**Comment by jinxx52** [comment]
同样的情况，已经头疼很多天了。插件加载顺序更改一遍也是同样的报错

**Comment by kexue-z** [comment]
可以详细说一下服务器是什么配置吗？如何复现等操作

**Comment by jinxx52** [comment]
> 可以详细说一下服务器是什么配置吗？如何复现等操作

配置情况的话4核4g 8Mbps的服务器情况是只要装了两个以上使用playwright截图的插件就不能正常使用插件，
但是这台服务器生产资料过多，我就用最低配的2核2g 5Mbps复现了

重装系统选择乌班图20.04版本，使用自带的python3.8重新安装playwright和nb-cli
报了两个很迷惑的错![-f430d4dd9ef7b25.png](https://user-images.githubusercontent.com/86406052/169607236-bf34f884-dd58-4105-8b91-756c0becc6b2.png)
这两个竟然互相冲突，不过应该影响不大

重新create一个bot，使用gocqhttp连接

安装htmlrender，然后先装一个插件尝试使用

这里我用的枝网查重，只有两个插件，在运行 
开始运行没有报错，然后尝试使用插件
![-6c1e1f8b8b6ceaf.png](https://user-images.githubusercontent.com/86406052/169610814-95b90093-d367-4bd9-82f9-029e3d590806.png)

然而复现了单个插件使用也会报同样的错误，但是我在之前的服务器上是两个以上的插件才会报错，这就很迷惑了
然后我尝试了其他的插件单个使用也会报类似的错误![-554cfd94ee31bb04.png](https://user-images.githubusercontent.com/86406052/169611277-1821bd5b-8378-4cc7-8c67-947dd8274d2b.png)

**Comment by jinxx52** [comment]
回头我自己写一个截图的插件试试，不自己动手确实不好理解，还是谢谢大佬了

**Comment by kexue-z** [comment]
不建议使用系统自带py环境运行bot 建议使用miniconda或者poetry

**Comment by benx1n** [comment]
我这边有群友也复现了这个问题
使用sudo nb run必现playwright Timeout，直接nb run就没问题
