### ISSUE TITLE
windows启动，产生以下报错，可能是playwright的问题？

### ISSUE THREAD

**Issue by yixue99** [kexue-z/nonebot-plugin-htmlrender#24]
![image](https://user-images.githubusercontent.com/50444999/170805245-7759e383-2c8d-4366-ace4-b3825dd2bb46.png)
大佬，这该怎么解决，拜谢

**Comment by kexue-z** [comment]
win 昨天我自己跑成功了 
py3.10.2 + poetry

**Comment by lonevle** [comment]
我也是一样的, 有法解决吗

**Comment by kexue-z** [comment]
https://github.com/kexue-z/nonebot-plugin-htmlrender/issues/25#issuecomment-1140840590
