### ISSUE TITLE
windows平台启动nonebot-plugin-htmlrender 报错 NotImplementedError

### ISSUE THREAD

**Issue by lonevle** [kexue-z/nonebot-plugin-htmlrender#25]
已经安装了playwright, 执行测试: python -m playwright codegen --target python -o baidu.py -b chromium https://www.baidu.com 正常
Python版本3.10.4, 这个报错是缺少什么还是哪里有问题?
方便的话, 可以出一个详细的windows安装教程吗

<details>
<summary>报错信息</summary>
![20220530144136](https://user-images.githubusercontent.com/48077551/170932269-e188c8cf-186b-4540-87f8-cbc60bf61f6b.png)

Package                    Version
-------------------------- -----------
aerich                     0.6.3
aiocache                   0.11.1
aiofiles                   0.8.0
aiohttp                    3.8.1
aiosignal                  1.2.0
aiosqlite                  0.17.0
anyio                      3.5.0
APScheduler                3.9.1
arrow                      1.2.2
asgiref                    3.5.0
async-timeout              4.0.2
asyncpg                    0.25.0
attrs                      21.4.0
bilireq                    0.1.2
binaryornot                0.4.4
CacheControl               0.12.11
cachy                      0.3.0
certifi                    2021.10.8
chardet                    4.0.0
charset-normalizer         2.0.12
cleo                       0.8.1
click                      8.1.2
clikit                     0.6.2
colorama                   0.4.4
cookiecutter               1.7.3
crashtest                  0.3.1
dictdiffer                 0.9.0
distlib                    0.3.4
Django                     4.0.4
emoji                      1.7.0
fastapi                    0.73.0
filelock                   3.7.0
fonttools                  4.33.3
frozenlist                 1.3.0
fuzzywuzzy                 0.18.0
greenlet                   1.1.2
h11                        0.12.0
haruka-bot                 1.3.6.post1
html5lib                   1.1
httpcore                   0.14.7
httptools                  0.4.0
httpx                      0.22.0
httpx-socks                0.7.3
idna                       3.3
imageio                    2.19.2
importlib-metadata         4.11.4
iso8601                    0.1.16
Jinja2                     3.1.1
jinja2-time                0.2.0
keyring                    23.5.1
lockfile                   0.12.2
loguru                     0.6.0
lxml                       4.8.0
Markdown                   3.3.7
MarkupSafe                 2.1.1
msgpack                    1.0.3
multidict                  6.0.2
nb-cli                     0.6.6
nonebot-adapter-onebot     2.0.0b1
nonebot-plugin-apscheduler 0.1.2
nonebot-plugin-htmlrender  0.0.5
nonebot-plugin-picsearcher 0.1.6rc2
nonebot-plugin-read-60s    0.2.4
nonebot2                   2.0.0b2
numpy                      1.22.3
opencv-contrib-python      4.5.5.64
opencv-python              4.5.5.64
packaging                  20.9
pastel                     0.2.1
pexpect                    4.8.0
Pillow                     9.1.1
pip                        22.0.4
pkginfo                    1.8.2
platformdirs               2.5.2
playwright                 1.22.0
poetry                     1.1.13
poetry-core                1.0.8
poyo                       0.5.0
prompt-toolkit             3.0.29
ptyprocess                 0.7.0
pyasn1                     0.4.8
pydantic                   1.9.0
pyee                       8.1.0
pyfiglet                   0.8.post1
Pygments                   2.12.0
pygtrie                    2.4.2
pylev                      1.4.0
pymdown-extensions         9.4
pyparsing                  3.0.9
pypika-tortoise            0.1.4
python-dateutil            2.8.2
python-dotenv              0.19.2
python-markdown-math       0.8
python-slugify             6.1.1
python-socks               2.0.3
pytz                       2022.1
pytz-deprecation-shim      0.1.0.post0
pywin32-ctypes             0.2.0
PyYAML                     6.0
requests                   2.27.1
requests-toolbelt          0.9.1
rfc3986                    1.5.0
rsa                        4.8
setuptools                 58.1.0
shellingham                1.4.0
six                        1.16.0
sniffio                    1.2.0
sqlparse                   0.4.2
starlette                  0.17.1
text-unidecode             1.3
tomlkit                    0.9.2
tortoise-orm               0.18.1
tqdm                       4.64.0
typing_extensions          4.1.1
tzdata                     2022.1
tzlocal                    4.2
urllib3                    1.26.9
uvicorn                    0.17.6
virtualenv                 20.14.1
watchgod                   0.8.2
wcwidth                    0.2.5
webencodings               0.5.1
websockets                 10.1
wfastcgi                   3.0.0
win32-setctime             1.1.0
yarl                       1.7.2
zipp                       3.8.0
</details>

**Comment by kexue-z** [comment]
我是用的官网下的py3.10 然后用poetry虚拟环境运行的 你可以试试

**Comment by kexue-z** [comment]
使用本项目中的 `example` 运行在 Win11 x64 中

## 使用Python版本和Pip

```
PS D:\git\nonebot-plugin-htmlrender\example> pip --version
pip 22.1.1 from C:\Users\27822\AppData\Local\Programs\Python\Python310\lib\site-packages\pip (python 3.10)
PS D:\git\nonebot-plugin-htmlrender\example> python --version
Python 3.10.4
```

## 使用的包
```
Package                   Version
------------------------- -----------
aiofiles                  0.8.0
anyio                     3.6.1
arrow                     1.2.2
asgiref                   3.5.2
binaryornot               0.4.4
certifi                   2022.5.18.1
chardet                   4.0.0
charset-normalizer        2.0.12
click                     8.1.3
colorama                  0.4.4
cookiecutter              1.7.3
fastapi                   0.78.0
greenlet                  1.1.2
h11                       0.12.0
httpcore                  0.15.0
httptools                 0.4.0
httpx                     0.23.0
idna                      3.3
Jinja2                    3.1.2
jinja2-time               0.2.0
loguru                    0.6.0
Markdown                  3.3.7
MarkupSafe                2.1.1
multidict                 6.0.2
nb-cli                    0.6.7
nonebot-adapter-onebot    2.0.0b1
nonebot-plugin-htmlrender 0.0.5
nonebot2                  2.0.0b3
Pillow                    9.1.1
pip                       22.1.1
playwright                1.22.0
poyo                      0.5.0
prompt-toolkit            3.0.29
pydantic                  1.9.1
pyee                      8.1.0
pyfiglet                  0.8.post1
Pygments                  2.12.0
pygtrie                   2.4.2
pymdown-extensions        9.4
python-dateutil           2.8.2
python-dotenv             0.20.0
python-markdown-math      0.8
python-slugify            6.1.2
PyYAML                    6.0
requests                  2.27.1
rfc3986                   1.5.0
setuptools                58.1.0
six                       1.16.0
sniffio                   1.2.0
starlette                 0.19.1
text-unidecode            1.3
tomlkit                   0.10.2
typing_extensions         4.2.0
urllib3                   1.26.9
uvicorn                   0.17.6
watchgod                  0.8.2
wcwidth                   0.2.5
websockets                10.1
win32-setctime            1.1.0
yarl                      1.7.2
```

## 直接运行

```
PS D:\git\nonebot-plugin-htmlrender\example> python .\bot.py
05-30 15:45:00 [SUCCESS] nonebot | NoneBot is initializing...
05-30 15:45:00 [INFO] nonebot | Current Env: dev
05-30 15:45:01 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_htmlrender"
05-30 15:45:01 [SUCCESS] nonebot | Succeeded to import "render"
05-30 15:45:01 [SUCCESS] nonebot | Running NoneBot...
05-30 15:45:01 [WARNING] uvicorn | Current configuration will not reload as not all conditions are met,please refer to documentation.
05-30 15:45:01 [INFO] uvicorn | Started server process [1380]
05-30 15:45:01 [INFO] uvicorn | Waiting for application startup.
05-30 15:45:02 [INFO] nonebot_plugin_htmlrender | Browser Started.
05-30 15:45:02 [INFO] uvicorn | Application startup complete.
05-30 15:45:02 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:9905 (Press CTRL+C to quit)
05-30 15:45:06 [INFO] uvicorn | ('192.168.0.49', 49408) - "WebSocket /onebot/v11/ws" [accepted]
05-30 15:45:06 [INFO] nonebot | OneBot V11 | Bot xxxxxx connected
05-30 15:45:06 [INFO] websockets | connection open
05-30 15:45:08 [SUCCESS] nonebot | ONEBOT V11 3571509319 | [message.group.normal]: Message -278508567 from xxxx@[群:xxxx] "/md2pic test"
05-30 15:45:08 [INFO] nonebot | Event will be handled by <Matcher from plugins.render, type=message, priority=1, temp=False>
05-30 15:45:10 [SUCCESS] nonebot | ONEBOT V11 3571509319 | [message_sent]: {'time': 1653896709, 'self_id': xxxxx, 'post_type': 'message_sent', 'sub_type': 'normal', 'message_type': 'group', 'user_id': xxxxx, 'message': '[CQ:image,file=f75d3877e541065d23e95e9091b0a6c5.image,url=https://gchat.qpic.cn/gchatpic_new/xxxx/xxxx-xx-F75D3xxxxx0A6C5/0?term=255,subType=0]', 'group_id': xxxx, 'message_id': xxx, 'raw_message': '[CQ:image,file=f75d3877e541065d23e95e9091b0a6c5.image,subType=0]', 'message_seq': 1472, 'font': 0, 'anonymous': None, 'sender': {'age': 0, 'area': '', 'card': '', 'level': '', 'nickname': 'Mikko', 'role': 'member', 'sex': 'unknown', 'title': '', 'user_id': 3571509319}}
05-30 15:45:10 [INFO] nonebot | Matcher <Matcher from plugins.render, type=message, priority=1, temp=False> running complete
05-30 15:45:15 [INFO] uvicorn | Shutting down
05-30 15:45:15 [WARNING] nonebot | OneBot V11 | WebSocket for Bot xxxx closed by peer
05-30 15:45:15 [INFO] websockets | connection closed
05-30 15:45:15 [INFO] uvicorn | Waiting for application shutdown.
05-30 15:45:15 [INFO] nonebot_plugin_htmlrender | Browser Stopped.
05-30 15:45:15 [INFO] uvicorn | Application shutdown complete.
05-30 15:45:15 [INFO] uvicorn | Finished server process [1380]
```

## 测试结果

发送成功

**Comment by lonevle** [comment]
目前测试是在 async_playwright().start() 时出现错误

**Comment by kexue-z** [comment]
在你配置文件里 `.env.dev` 或 `.env.pord` 里面找到 `FASTAPI_RELOAD=true` 把他改成 `FASTAPI_RELOAD=false`

**Comment by lonevle** [comment]
非常感谢, 目前配置FASTAPI_RELOAD=false后, 问题已解决

**Comment by kexue-z** [comment]
去找真寻提issue 他应该用不到我的插件吧

而且这个好像是win的问题

**Comment by RShock** [comment]
真寻没用这个插件，是我自己开发用的
