### ISSUE TITLE
提示安装chromium报错退出

### ISSUE THREAD

**Issue by Teares** [kexue-z/nonebot-plugin-htmlrender#26]
![image](https://user-images.githubusercontent.com/81464000/174436500-9451b32c-98e4-4352-9a9c-8289504fcfd8.png)
![image](https://user-images.githubusercontent.com/81464000/174436511-fd7a588f-0fae-4ad6-a1e2-a2f757fac9ea.png)
![image](https://user-images.githubusercontent.com/81464000/174436562-39915a2e-6b78-457e-9512-fdcd0a6446b0.png)

插件提示`06-18 07:57:15 [INFO] nonebot_plugin_htmlrender | 正在安装 chromium`
后直接报`06-18 07:57:17 [ERROR] uvicorn | Application startup failed. Exiting.`退出,重装无法解决

**Comment by kexue-z** [comment]
我知道 看这里  https://github.com/kexue-z/nonebot-plugin-htmlrender/blob/master/README.md

**Comment by Teares** [comment]
> 我知道 看这里 https://github.com/kexue-z/nonebot-plugin-htmlrender/blob/master/README.md

试过了，依然这样:((((((
`06-19 08:48:58 [ERROR] uvicorn | Application startup failed. Exiting.`
![image](https://user-images.githubusercontent.com/81464000/174481761-1ec6dc45-3a28-4b8a-a2fc-6351646cf1f0.png)
![image](https://user-images.githubusercontent.com/81464000/174481803-f7d14bb4-018c-4aff-b5e4-3a8502947316.png)
![image](https://user-images.githubusercontent.com/81464000/174481813-28da9beb-6690-4ccc-8999-8242a88a96df.png)
![image](https://user-images.githubusercontent.com/81464000/174481819-222b471e-fe40-46df-9e16-ff0bfda66384.png)

**Comment by kexue-z** [comment]
你这是啥系统 或者可以使用终极的解决办法 《docker》 你找找我仓库里面有的

**Comment by kexue-z** [comment]
等等 你是在bot.py 里面载入了吗 建议把这个放到前面

**Comment by Teares** [comment]
> 等等 你是在bot.py 里面载入了吗 建议把这个放到前面

放最前面引入成功了
![image](https://user-images.githubusercontent.com/81464000/174482056-3a5262b7-baec-4aa9-a6b6-3a80d1238c3f.png)

不过下面提示`06-19 08:57:16 [INFO] nonebot_plugin_htmlrender | 正在安装 chromium`后
还是和上面一样报`06-19 08:57:18 [ERROR] uvicorn | Application startup failed. Exiting.`

**Comment by kexue-z** [comment]
怀疑是环境依赖没有装好 你单独写一个运行playwright试试
