### ISSUE TITLE
图片生成之后 顶部会留白

### ISSUE THREAD

**Issue by nicklly** [kexue-z/nonebot-plugin-htmlrender#31]
RT，当截图完成并发送输出 图片最顶部会留白，请问有解决方法么？
![Y(VVDB8XFVSDS8LOM5 TDQP](https://user-images.githubusercontent.com/17716585/192303978-b659427a-90d1-4863-a47e-2b6945983d9e.png)

**Comment by kexue-z** [comment]
可能是这个网页本身的问题，尝试导出html代码在自己的浏览器上查看

**Comment by nicklly** [comment]
> 可能是这个网页本身的问题，尝试导出html代码在自己的浏览器上查看

尝试过了 直接访问html是没有顶部留白的问题

**Comment by monsterxcn** [comment]
浏览器有个叫 user agent stylesheet 的东西，比如 Chrome 的这个样式表里有个：

```css
body {
    display: block;
    margin: 8px;
}
```

我觉得是这里的原因。以前我也遇到过，自己预览确实没有，但让 htmlrender 截图就会有白边。

你可以试试自己给 body 定义下 `margin: 0px`，应该就没有白边了。
