### ISSUE TITLE
导入失败 No module named 'nonebot_plugin_htmlrender.config'

### ISSUE THREAD

**Issue by a930389426** [kexue-z/nonebot-plugin-htmlrender#32]
如题

**Comment by a930389426** [comment]
![QQ截图20221011174852](https://user-images.githubusercontent.com/59648220/195057899-558ec5d7-c122-4b03-a9fc-785c40102738.png)

**Comment by DadddyWang** [comment]
尝试把插件目录下的browser.py文件中的 
from nonebot_plugin_htmlrender.config import Config  语句
修改为
from .config import Config

**Comment by a930389426** [comment]
> 尝试把插件目录下的browser.py文件中的 from nonebot_plugin_htmlrender.config import Config 语句 修改为 from .config import Config 我是这样解决的

解决了，谢谢大佬

**Comment by a930389426** [comment]
> ![image](https://user-images.githubusercontent.com/108965579/197732689-0fa1505c-83af-4587-9f19-443a5844dadf.png) 我遇到类似的问题，改了文件之后也这样
你不会是把from nonebot_plugin_htmlrender.config import Config 
改成了
from nonebot_plugin_htmlrender import Config吧

**Comment by a930389426** [comment]
> ![image](https://user-images.githubusercontent.com/108965579/197732689-0fa1505c-83af-4587-9f19-443a5844dadf.png) 我遇到类似的问题，改了文件之后也这样

你不会是把from nonebot_plugin_htmlrender.config import Config
改成了
from nonebot_plugin_htmlrender import Config吧

**Comment by DadddyWang** [comment]
> ![image](https://user-images.githubusercontent.com/108965579/197732689-0fa1505c-83af-4587-9f19-443a5844dadf.png) 我遇到类似的问题，改了文件之后也这样

代码方便贴一下么

**Comment by a930389426** [comment]
> > ![image](https://user-images.githubusercontent.com/108965579/197732689-0fa1505c-83af-4587-9f19-443a5844dadf.png) 我遇到类似的问题，改了文件之后也这样
> 
> 代码方便贴一下么

![image](https://user-images.githubusercontent.com/59648220/198209552-989a7d28-8268-46eb-a1e7-f4ed701f2809.png)

**Comment by DadddyWang** [comment]
> ![image](https://user-images.githubusercontent.com/108965579/197732689-0fa1505c-83af-4587-9f19-443a5844dadf.png) 我遇到类似的问题，改了文件之后也这样



> > > ![image](https://user-images.githubusercontent.com/108965579/197732689-0fa1505c-83af-4587-9f19-443a5844dadf.png) 我遇到类似的问题，改了文件之后也这样
> > 
> > 
> > 代码方便贴一下么
> 
> ![image](https://user-images.githubusercontent.com/59648220/198209552-989a7d28-8268-46eb-a1e7-f4ed701f2809.png)

看上面老哥的报错似乎那一行没改

**Comment by DadddyWang** [comment]
> ![image](https://user-images.githubusercontent.com/108965579/197732689-0fa1505c-83af-4587-9f19-443a5844dadf.png) 我遇到类似的问题，改了文件之后也这样



> > > ![image](https://user-images.githubusercontent.com/108965579/197732689-0fa1505c-83af-4587-9f19-443a5844dadf.png) 我遇到类似的问题，改了文件之后也这样
> > 
> > 
> > 代码方便贴一下么
> 
> ![image](https://user-images.githubusercontent.com/59648220/198209552-989a7d28-8268-46eb-a1e7-f4ed701f2809.png)

看上面老哥的报错似乎那一行没改

**Comment by Nenot233** [comment]
非常感谢，我细细研究之后发现是改错行了，不好意思

**Comment by DadddyWang** [comment]
> 非常感谢，我细细研究之后发现是改错行了，不好意思

没事 我就说看报错不对 看起来没改^-^

**Comment by kexue-z** [comment]
发生甚么事了？

**Comment by a930389426** [comment]
> 发生甚么事了？

就上面有个兄弟出bug后改代码改错行了
