### ISSUE TITLE
图片生成失败

### ISSUE THREAD

**Issue by hellofinch** [kexue-z/nonebot-plugin-htmlrender#35]
使用的版本是0.2.0.1
调用方法后抛出异常，没有返回值。控制台日志如下：
![image](https://user-images.githubusercontent.com/42131198/201278565-edcdb0c3-73d9-4e68-b8b2-4ec9d7a068a7.png)

**Comment by kexue-z** [comment]
具体什么情况我不太了解 不过按照图上说，是没有载入到资源。

试试换成firefox玄学解决一下？

**Comment by hellofinch** [comment]
OK 我试一下

**Comment by hellofinch** [comment]
![image](https://user-images.githubusercontent.com/42131198/201337881-18ce4f07-cd19-4f8c-befe-e636dd382062.png)
![image](https://user-images.githubusercontent.com/42131198/201337920-dc4eb29f-881a-4544-b111-0e41da9d63c8.png)
这个文件是有的，我换成firefox了也不行。

**Comment by hellofinch** [comment]
确实，感谢
