### ISSUE TITLE
希望可以更新一下依赖版本

### ISSUE THREAD

**Issue by Glospred** [kexue-z/nonebot-plugin-htmlrender#36]
我使用的bot是https://github.com/HibiKier/zhenxun_bot
更新1.6.5后依赖更新，htmlrender就无法加载了
[requirements.txt](https://github.com/kexue-z/nonebot-plugin-htmlrender/files/10101949/requirements.txt)
这是从toml export出的requirements，希望跟进一下依赖

**Comment by kexue-z** [comment]
真寻也不需要用我这个插件吧 他自己写好的啊？

而且你这 requirements.txt 也不是给人看的。。。。

**Comment by Glospred** [comment]
啊，那问题大概在于用的插件太久没更新了...?
总之感谢回复，我自己再去了解下吧
