### ISSUE TITLE
playwright一直更新是怎么回事啊？

### ISSUE THREAD

**Issue by krasus1995** [kexue-z/nonebot-plugin-htmlrender#37]
![5%LZX5PMG(EBMLAUIAY~{1S](https://user-images.githubusercontent.com/97447697/205458920-61fd381f-16c3-4f7c-883e-946d086070c9.png)

**Comment by kexue-z** [comment]
在你的运行环境下 

```sh
python -m playwright install
```

**Comment by krasus1995** [comment]
傻逼playwright一直更新无限循环，我回退到1.23版本就正常了

**Comment by kexue-z** [comment]
可以尝试直接在不启动bot的时候playwright install一下？具体我不清楚什么情况

**Comment by krasus1995** [comment]
![RFUB5%$ASK75EL`CGWQLO R](https://user-images.githubusercontent.com/97447697/206127487-3bf1bf54-4ef0-4758-b02a-b12256bd6ad4.png)
每次启动都要更新这个chromium，然后chromium更新完了，提示让下载playwright，启动失败

**Comment by kexue-z** [comment]
可能是镜像源的问题，换一个试试
