### ISSUE TITLE
请求添加更自由的截图配置

### ISSUE THREAD

**Issue by monsterxcn** [kexue-z/nonebot-plugin-htmlrender#38]
https://github.com/kexue-z/nonebot-plugin-htmlrender/blob/7da5431ecb17f657c6ea2e8b504307e86cf22ebd/nonebot_plugin_htmlrender/date_source.py#L142-L163

我看到当前插件通过 `html_to_pic()` 渲染 HTML 截图时，无法自由定义图像的 `type="jpeg"`、`quality=90` 等配置，只能返回 PNG 图片，这样图片体积通常较大。能否为相关函数添加对应的参数，让用户可以更自由地决定这些配置呢？

虽然说如果在编写插件时使用 `get_new_page()` 自行处理能实现，但这样通常不得不另外 `import jinjia2`（获取 `html_to_pic()` 的 `html`）等等。我希望能只用一行 `import` 就搞定，比如我现在是这样用的：

```python
from nonebot_plugin_htmlrender import template_to_pic

async def something():
    # ...
    
    return await template_to_pic(...)
    # 想要的：
    # return await template_to_pic(..., type="jpeg", quality=80)
```

**Comment by kexue-z** [comment]
那还要啥参数捏。。。

https://github.com/kexue-z/nonebot-plugin-htmlrender/commit/a39347ea50dd07cef20e3e5f59a06ce741375f23

**Comment by monsterxcn** [comment]
就是 [Selectors](https://playwright.dev/python/docs/selectors)。插件当前的截图是 `full_page=True` 限制了只能全屏截图，期待能支持一下指定选择器的 [Element screenshot](https://playwright.dev/python/docs/screenshots#element-screenshot)。

**Comment by kexue-z** [comment]
我发现了，你没读源码！

**Comment by monsterxcn** [comment]
🤣我只简单看了看栗子，彳亍，原来是有的。

但这个 `capture_element` 里面的 `screenshot` 是不是忘记传 `type` 和 `quality` 了

**Comment by kexue-z** [comment]
确实，立即PR！
