### ISSUE TITLE
AttributeError: module 'attr' has no attribute 'frozen'

### ISSUE THREAD

**Issue by Chanpoe** [kexue-z/nonebot-plugin-htmlrender#43]
导入插件时遇到问题，报错如下
![image](https://user-images.githubusercontent.com/84487466/215535717-32315d3d-43ae-434e-a502-4ef0b6499bd1.png)

**Comment by Chanpoe** [comment]
报错补充

**Comment by kexue-z** [comment]
这报错从哪里提出来的 我都不知道。。。

**Comment by kexue-z** [comment]
你这个插件就没装上啊

**Comment by xxtg666** [comment]
> 

加载不了，上面一段报错和他一样的

**Comment by kexue-z** [comment]
`pip list` 一下

**Comment by xxtg666** [comment]
Package                    Version             
-------------------------- --------------------
aiocqhttp                  1.4.3               
aiofiles                   22.1.0              
aiohttp                    3.8.3               
aiosignal                  1.3.1               
anyio                      3.6.2               
APScheduler                3.10.0              
arrow                      1.2.3               
async-generator            1.10                
async-timeout              4.0.2               
attrs                      19.3.0              
Automat                    0.8.0               
backports.zoneinfo         0.2.1               
binaryornot                0.4.4               
blinker                    1.4                 
certifi                    2022.12.7           
chardet                    3.0.4               
charset-normalizer         2.1.1               
click                      8.1.3               
cloud-init                 22.4.2              
colorama                   0.4.3               
command-not-found          0.3                 
configobj                  5.0.6               
constantly                 15.1.0              
cookiecutter               1.7.3               
cryptography               2.8                 
dbus-python                1.2.16              
discord.py                 2.1.0               
distro                     1.4.0               
distro-info                0.23ubuntu1         
entrypoints                0.3                 
exceptiongroup             1.1.0               
expandvars                 0.9.0               
fastapi                    0.88.0              
Flask                      2.2.2               
frozenlist                 1.3.3               
greenlet                   2.0.1               
h11                        0.14.0              
h2                         4.1.0               
hpack                      4.0.0               
httpcore                   0.16.3              
httplib2                   0.14.0              
httptools                  0.5.0               
httpx                      0.23.1              
hypercorn                  0.14.3              
hyperframe                 6.0.1               
hyperlink                  19.0.0              
idna                       2.8                 
importlib-metadata         5.2.0               
incremental                16.10.1             
itsdangerous               2.1.2               
Jinja2                     3.1.2               
jinja2-time                0.2.0               
jsonpatch                  1.22                
jsonpointer                2.0                 
jsonschema                 3.2.0               
keyring                    18.0.1              
language-selector          0.1                 
launchpadlib               1.10.13             
lazr.restfulclient         0.14.2              
lazr.uri                   1.0.3               
loguru                     0.6.0               
Markdown                   3.4.1               
MarkupSafe                 2.1.1               
more-itertools             4.2.0               
msgpack                    1.0.4               
multidict                  6.0.4               
nb-cli                     0.6.8               
netifaces                  0.10.4              
nonebot-adapter-onebot     2.2.0               
nonebot-plugin-apscheduler 0.2.0               
nonebot-plugin-htmlrender  0.2.0.3             
nonebot2                   2.0.0rc2            
oauthlib                   3.1.0               
outcome                    1.2.0               
pexpect                    4.6.0               
Pillow                     9.4.0               
pip                        20.0.2              
playwright                 1.29.1              
poyo                       0.5.0               
prettytable                3.6.0               
priority                   2.0.0               
prompt-toolkit             3.0.36              
psutil                     5.9.4               
pyasn1                     0.4.2               
pyasn1-modules             0.2.1               
pydantic                   1.10.2              
pyecharts                  2.0.1               
pyee                       9.0.4               
pyfiglet                   0.8.post1           
Pygments                   2.14.0              
PyGObject                  3.36.0              
pygtrie                    2.5.0               
PyHamcrest                 1.9.0               
PyJWT                      1.7.1               
pymacaroons                0.13.0              
pymdown-extensions         9.9.2               
PyNaCl                     1.3.0               
pyOpenSSL                  19.0.0              
pyparted                   3.11.2              
pyrsistent                 0.15.5              
pyserial                   3.4                 
PySocks                    1.7.1               
python-apt                 2.0.0+ubuntu0.20.4.8
python-dateutil            2.8.2               
python-debian              0.1.36ubuntu1       
python-dotenv              0.21.0              
python-markdown-math       0.8                 
python-slugify             7.0.0               
pytz                       2022.7.1            
pytz-deprecation-shim      0.1.0.post0         
PyYAML                     5.3.1               
quart                      0.18.3              
requests                   2.28.1              
requests-unixsocket        0.2.0               
rfc3986                    1.5.0               
SecretStorage              2.3.1               
selenium                   4.8.0               
service-identity           18.1.0              
setuptools                 45.2.0              
simplejson                 3.16.0              
six                        1.14.0              
snapshot-selenium          0.0.2               
sniffio                    1.3.0               
sortedcontainers           2.4.0               
sos                        4.4                 
ssh-import-id              5.10                
starlette                  0.22.0              
systemd-python             234                 
text-unidecode             1.3                 
toml                       0.10.2              
tomlkit                    0.11.6              
trio                       0.22.0              
trio-websocket             0.9.2               
Twisted                    18.9.0              
typing-extensions          4.4.0               
tzdata                     2022.7              
tzlocal                    4.2                 
ubuntu-advantage-tools     27.12               
ufw                        0.36                
unattended-upgrades        0.1                 
urllib3                    1.26.14             
uvicorn                    0.20.0              
uvloop                     0.17.0              
wadllib                    1.3.3               
WALinuxAgent               2.2.46              
watchfiles                 0.18.1              
wcwidth                    0.2.5               
websockets                 10.4                
Werkzeug                   2.2.2               
wheel                      0.34.2              
wsproto                    1.2.0               
yarl                       1.8.2               
zipp                       1.0.0               
zope.interface             4.7.1

**Comment by xxtg666** [comment]
（其他的插件是直接放进`src/plugins`里装的，因为这个会报错就单独`nb plugin install`装的

**Comment by kexue-z** [comment]
，，，，，你如果正常安装 我这个插件会作为依赖自动载入的 不需要额外载入

**Comment by xxtg666** [comment]
那我把需要这个的另外几个插件用pip装一下试试

**Comment by xxtg666** [comment]
是python版本问题，换成3.10就可以了

**Comment by Chanpoe** [comment]
> 是python版本问题，换成3.10就可以了

好的，我试一下

**Comment by Chanpoe** [comment]
> ，，，，，你如果正常安装 我这个插件会作为依赖自动载入的 不需要额外载入

感谢指点

**Comment by monsterxcn** [comment]
https://github.com/monsterxcn/nonebot-plugin-gspanel/issues/36#issuecomment-1425890563
