### ISSUE TITLE
能否放宽aiofiles依赖的版本限制

### ISSUE THREAD

**Issue by bridgeL** [kexue-z/nonebot-plugin-htmlrender#44]
aiofiles在Sep 5, 2022时发布了22.1.0版本，商店里有些插件使用了该版本，导致安装htmlrender时发生依赖冲突

htmlrender是否可以放宽依赖要求，支持22.1.0的aiofiles呢

**Comment by kexue-z** [comment]
更新了

**Comment by bridgeL** [comment]
感谢！
