### ISSUE TITLE
纯编程小白，想问下安装该插件后启动期间报这个错

### ISSUE THREAD

**Issue by wjzlyr** [kexue-z/nonebot-plugin-htmlrender#47]
[ERROR] uuicornH pplication startup f ailed. Exiting-

**Comment by wjzlyr** [comment]
02-22 18:32:01 [INFO] nonebot_plugin_htmlrender | 使用 chromium 启动
02-22 18:32:03 [INFO] nonebot_plugin_htmlrender | 使用镜像源进行下载
02-22 18:32:03 [INFO] nonebot_plugin_htmlrender | 正在安装 chromium
02-22 18:32:03 [INFO] nonebot_plugin_htmlrender | 正在安装依赖

Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             NoChangeNeeded {}


02-22 18:32:10 [INFO] nonebot_plugin_htmlrender | 使用 chromium 启动
02-22 18:32:12 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 38, in init
    _browser = await launch_browser(**kwargs)
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 56, in launch_browser
    return await _playwright.chromium.launch(**kwargs)
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\playwright\async_api\_generated.py", line 14369, in launch
    await self._impl_obj.launch(
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\playwright\_impl\_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\playwright\_impl\_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\playwright\_impl\_connection.py", line 419, in wrap_api_call
    return await cb()
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\playwright\_impl\_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> C:\Users\Administrator\AppData\Local\ms-playwright\chromium-1048\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-backg
round-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update
 --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRoutePr
ovider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-
blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autor
un --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\ADMINI~1\AppData\Local\Tem
p\2\playwright_chromiumdev_profile-n3xFjm --remote-debugging-pipe --no-startup-window
<launched> pid=2608
[pid=2608][err] [0222/183202.650:ERROR:main_dll_loader_win.cc(109)] Failed to load Chrome DLL from C:\Users\Administrator\AppData\Local\ms-playwright\chromium-1048\chrome-win\chrome.dll: �Ҳ���ָ���ĳ��� (0x7F)
=========================== logs ===========================
<launching> C:\Users\Administrator\AppData\Local\ms-playwright\chromium-1048\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-backg
round-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update
 --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRoutePr
ovider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-
blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autor
un --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\ADMINI~1\AppData\Local\Tem
p\2\playwright_chromiumdev_profile-n3xFjm --remote-debugging-pipe --no-startup-window
<launched> pid=2608
[pid=2608][err] [0222/183202.650:ERROR:main_dll_loader_win.cc(109)] Failed to load Chrome DLL from C:\Users\Administrator\AppData\Local\ms-playwright\chromium-1048\chrome-win\chrome.dll: �Ҳ���ָ���ĳ��� (0x7F)
============================================================

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\nonebot_plugin_htmlrender\__init__.py", line 25, in init
    browser = await get_browser(**kwargs)
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 60, in get_browser
    return _browser if _browser and _browser.is_connected() else await init(**kwargs)
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 41, in init
    _browser = await launch_browser(**kwargs)
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\nonebot_plugin_htmlrender\browser.py", line 56, in launch_browser
    return await _playwright.chromium.launch(**kwargs)
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\playwright\async_api\_generated.py", line 14369, in launch
    await self._impl_obj.launch(
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\playwright\_impl\_browser_type.py", line 93, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\playwright\_impl\_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\playwright\_impl\_connection.py", line 419, in wrap_api_call
    return await cb()
  File "C:\Users\Administrator\anaconda3\envs\py3-10-9\lib\site-packages\playwright\_impl\_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> C:\Users\Administrator\AppData\Local\ms-playwright\chromium-1048\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-backg
round-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update
 --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRoutePr
ovider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-
blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autor
un --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\ADMINI~1\AppData\Local\Tem
p\2\playwright_chromiumdev_profile-xSWxqd --remote-debugging-pipe --no-startup-window
<launched> pid=3456
[pid=3456][err] [0222/183211.890:ERROR:main_dll_loader_win.cc(109)] Failed to load Chrome DLL from C:\Users\Administrator\AppData\Local\ms-playwright\chromium-1048\chrome-win\chrome.dll: �Ҳ���ָ���ĳ��� (0x7F)
=========================== logs ===========================
<launching> C:\Users\Administrator\AppData\Local\ms-playwright\chromium-1048\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-backg
round-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update
 --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRoutePr
ovider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-
blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autor
un --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\ADMINI~1\AppData\Local\Tem
p\2\playwright_chromiumdev_profile-xSWxqd --remote-debugging-pipe --no-startup-window
<launched> pid=3456
[pid=3456][err] [0222/183211.890:ERROR:main_dll_loader_win.cc(109)] Failed to load Chrome DLL from C:\Users\Administrator\AppData\Local\ms-playwright\chromium-1048\chrome-win\chrome.dll: �Ҳ���ָ���ĳ��� (0x7F)
============================================================

02-22 18:32:12 [ERROR] uvicorn | Application startup failed. Exiting.

**Comment by kexue-z** [comment]
建议截图。这样我看不清，眼花

**Comment by wjzlyr** [comment]
![QQ图片20230222182641](https://user-images.githubusercontent.com/58624426/221344113-11096295-feac-44c9-af33-4af2872f0aa8.png)
呐，这样能看到吗

**Comment by kexue-z** [comment]
没有遇到这种问题。估计是系统环境的问题。

**Comment by monsterxcn** [comment]
这问题前几天也有人问我，参考 https://github.com/microsoft/playwright/issues/21490#issuecomment-1460739580 这个回复：系统的浏览器安装似乎已经损坏，可能是受反病毒软件或过于严格的安全策略影响。完全删除 `C:\Users\Administrator\AppData\Local\ms-playwright\chromium-1048\` 文件夹然后重启试试

**Comment by small-bili** [comment]
我也出现了这个问题，但是是在腾讯云上的windows server 2012 r2上出现了这问题，但是本地部署没有，我根据楼上的说法把本地的\chromium-1055d\chromium-win文件夹复制到Windows server上就解决问题了

**Comment by kexue-z** [comment]
都是 winserver 的问题 新版的不支持winserver了  建议升级 或者使用linux系统（
