### ISSUE TITLE
使用htmlrender会导致nb的--reload参数在重启时卡死

### ISSUE THREAD

**Issue by forchannot** [kexue-z/nonebot-plugin-htmlrender#49]
经过测试了，只有加载了带htmlrender的插件才会这样，可能是由于上游playwright引起的

**Comment by forchannot** [comment]
补充：环境为windows server2022服务器，python版本3.10.0，htmlrender版本为0.2.0.3

**Comment by MeetWq** [comment]
https://github.com/nonebot/nonebot2/issues/1654

**Comment by kexue-z** [comment]
使用playwright的同时不能使用reload参数，这是Windows的特性决定的。nb文档也有说

**Comment by lulu666lulu** [comment]
也会导致Ctrl+C退出卡死，加不加reload都一样，怀疑是playwrighr退出出现问题，能否修复一下？

**Comment by kexue-z** [comment]
https://github.com/microsoft/playwright-python/issues/1170

我觉得应该是这个
