### ISSUE TITLE
建议降低python依赖版本

### ISSUE THREAD

**Issue by MeetWq** [kexue-z/nonebot-plugin-htmlrender#5]

**Comment by kexue-z** [comment]
哦！ 每次都用的默认3.9 每次都没有改（

**Comment by kexue-z** [comment]
https://github.com/kexue-z/nonebot-plugin-htmlrender/commit/5faa4161bc0e8e2284f8e795c93b0b7e18f57a6c
已发布 `0.0.3.1`
