### ISSUE TITLE
使用插件计算原神队伍伤害报错

### ISSUE THREAD

**Issue by yeyuProject** [kexue-z/nonebot-plugin-htmlrender#50]
0|Miao-Yun | /root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/playwright/driver/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/playwright/driver/node)
0|Miao-Yun | /root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/playwright/driver/node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/playwright/driver/node)
0|Miao-Yun | /root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/playwright/driver/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/playwright/driver/node)
0|Miao-Yun | /root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/playwright/driver/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/playwright/driver/node)
0|Miao-Yun | /root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/playwright/driver/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/playwright/driver/node)
0|Miao-Yun | /root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/playwright/driver/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/playwright/driver/node)
0|Miao-Yun | [PyBot][02:40:42.344][ERROR] [message]Running Matcher(type='message', module=nonebot_plugin_gspanel) failed.
0|Miao-Yun | Traceback (most recent call last):
0|Miao-Yun |   File "main.py", line 17, in <module>
0|Miao-Yun |     yunzai_nonebot.run()
0|Miao-Yun |   File "/root/robot/Miao-Yunzai/plugins/py-plugin/yunzai_nonebot/__init__.py", line 31, in run
0|Miao-Yun |     nonebot.run(*args, **kwargs)
0|Miao-Yun |   File "/root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/nonebot/__init__.py", line 273, in run
0|Miao-Yun |     get_driver().run(*args, **kwargs)
0|Miao-Yun |   File "/root/robot/Miao-Yunzai/plugins/py-plugin/yunzai_nonebot/hijack/driver.py", line 42, in run
0|Miao-Yun |     loop.run_until_complete(self.serve())
0|Miao-Yun |   File "/usr/local/python3/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
0|Miao-Yun |     self.run_forever()
0|Miao-Yun |   File "/usr/local/python3/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
0|Miao-Yun |     self._run_once()
0|Miao-Yun |   File "/usr/local/python3/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
0|Miao-Yun |     handle._run()
0|Miao-Yun |   File "/usr/local/python3/lib/python3.8/asyncio/events.py", line 81, in _run
0|Miao-Yun |     self._context.run(self._callback, *self._args)
0|Miao-Yun |   File "/root/robot/Miao-Yunzai/plugins/py-plugin/yunzai_nonebot/hijack/message.py", line 10, in wrapper
0|Miao-Yun |     return await func(*args, **kwargs)
0|Miao-Yun |   File "/root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 141, in _check_matcher
0|Miao-Yun |     await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
0|Miao-Yun | > File "/root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/nonebot/message.py", line 187, in _run_matcher
0|Miao-Yun |     await matcher.run(bot, event, state, stack, dependency_cache)
0|Miao-Yun |   File "/root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 732, in run
0|Miao-Yun |     await self.simple_run(bot, event, state, stack, dependency_cache)
0|Miao-Yun |   File "/root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/nonebot/internal/matcher/matcher.py", line 707, in simple_run
0|Miao-Yun |     await handler(
0|Miao-Yun |   File "/root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
0|Miao-Yun |     return await cast(Callable[..., Awaitable[R]], self.call)(**values)
0|Miao-Yun |   File "/root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/nonebot_plugin_gspanel/__init__.py", line 79, in team_handle
0|Miao-Yun |     rt = await getTeam(uid, chars, showDetail)
0|Miao-Yun |   File "/root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/nonebot_plugin_gspanel/data_source.py", line 384, in getTeam
0|Miao-Yun |     return await template_to_pic(
0|Miao-Yun |   File "/root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/nonebot_plugin_htmlrender/data_source.py", line 233, in template_to_pic
0|Miao-Yun |     return await html_to_pic(
0|Miao-Yun |   File "/root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/nonebot_plugin_htmlrender/data_source.py", line 187, in html_to_pic
0|Miao-Yun |     async with get_new_page(**kwargs) as page:
0|Miao-Yun |   File "/usr/local/python3/lib/python3.8/contextlib.py", line 171, in __aenter__
0|Miao-Yun |     return await self.gen.__anext__()
0|Miao-Yun |   File "/root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/nonebot_plugin_htmlrender/browser.py", line 65, in get_new_page
0|Miao-Yun |     browser = await get_browser()
0|Miao-Yun |   File "/root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/nonebot_plugin_htmlrender/browser.py", line 60, in get_browser
0|Miao-Yun |     return _browser if _browser and _browser.is_connected() else await init(**kwargs)
0|Miao-Yun |   File "/root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/nonebot_plugin_htmlrender/browser.py", line 36, in init
0|Miao-Yun |     _playwright = await async_playwright().start()
0|Miao-Yun |   File "/root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/playwright/async_api/_context_manager.py", line 51, in start
0|Miao-Yun |     return await self.__aenter__()
0|Miao-Yun |   File "/root/.cache/pypoetry/virtualenvs/py-plugin-0fRIzhtO-py3.8/lib/python3.8/site-packages/playwright/async_api/_context_manager.py", line 46, in __aenter__
0|Miao-Yun |     playwright = AsyncPlaywright(next(iter(done)).result())
0|Miao-Yun | Exception: Connection closed while reading from the driver

**Comment by kexue-z** [comment]
看文档（
