### ISSUE TITLE
安装依赖chrome后，报错

### ISSUE THREAD

**Issue by Cvandia** [kexue-z/nonebot-plugin-htmlrender#51]
![image](https://user-images.githubusercontent.com/106718176/233779946-3943dad5-a916-4e78-b6a4-51d4e743e5ed.png)
![image](https://user-images.githubusercontent.com/106718176/233779965-2b440aca-271c-4c42-b7c5-b43823efe10c.png)

**Comment by Cvandia** [comment]
貌似是windows 2012 server已不支持新版本的chromium，尝试回退chromium版本覆盖后修护bug

**Comment by Agnes4m** [comment]
同样的问题+1

**Comment by Cvandia** [comment]
> 可能同样的问题+1，已使用`playwright install`后如下报错，似乎是无法读取chromium,也是win2012
> ![image](https://user-images.githubusercontent.com/70925546/233820440-4aa2a63d-09b2-4954-a562-3611f2025cdd.png)
> ![image](https://user-images.githubusercontent.com/70925546/233820447-3e2ebf87-dea2-49c6-98a1-43f5a062e381.png)
> 

可以尝试回退chromium版本，覆盖你安装的新版本

**Comment by Agnes4m** [comment]
直接使用旧版本会导致自动下新版本然后继续报错，
覆盖的话试了1054,1050都不行仍然报错，请问退回哪个版本才可以？
![image](https://user-images.githubusercontent.com/70925546/233827515-f5f74299-dea2-4ada-baca-fc2f7f1194d6.png)

**Comment by Cvandia** [comment]
> 
我回退的版本有点老，尽量往前面的试一下吧qwq

**Comment by Cvandia** [comment]
> 直接使用旧版本会导致自动下新版本然后继续报错， 覆盖的话试了1054,1050都不行仍然报错，请问退回哪个版本才可以？ ![image](https://user-images.githubusercontent.com/70925546/233827515-f5f74299-dea2-4ada-baca-fc2f7f1194d6.png)

不行可以换firefox，新的chromium不支持winserver 2012了
