### ISSUE TITLE
无法启动playwright，会默认重新下载失败报错

### ISSUE THREAD

**Issue by Agnes4m** [kexue-z/nonebot-plugin-htmlrender#52]
#51 同样的问题，但是我没办法解决，只能另开一个iss了。
系统： win2012
py：3.9.12
nb：2.0.0rc4
nonebot-plugin-htmlrender：0.2.0.3
使用`playwright install`正确的安装1055后，会出现启动的时候，自动下载然后失败报错。
我尝试 #51 的方法倒版本并没有解决

## 以下是报错

![image](https://user-images.githubusercontent.com/70925546/233820440-4aa2a63d-09b2-4954-a562-3611f2025cdd.png)
![image](https://user-images.githubusercontent.com/70925546/233820447-3e2ebf87-dea2-49c6-98a1-43f5a062e381.png)

**Comment by Agnes4m** [comment]
上面是在调用的时候会报错，现在是启动时就报错，并终止nb
![image](https://user-images.githubusercontent.com/70925546/233955883-245612aa-10a2-4458-bf02-96631ab9e008.png)

**Comment by kexue-z** [comment]
不要用winserver了，来随便用一个linux都好（

**Comment by Agnes4m** [comment]
> 不要用winserver了，来随便用一个linux都好（

 更换firefox内核解决问题了，建议修改当服务器是win的时候优先使用firefox内核
