### ISSUE TITLE
version `GLIBC_2.28' not found

### ISSUE THREAD

**Issue by verynewabie** [kexue-z/nonebot-plugin-htmlrender#53]
如题，遇到这个问题后我去按照网上教程升级gcc，安装GLIBC_2.28，结果遇到一些问题，导致我的bash失效，ls，cd这些最基础的指令都无法使用，重启后服务器无法ssh登录，寄。

**Comment by verynewabie** [comment]
我恨你，centos7.6。

**Comment by kexue-z** [comment]
用docker啦多香啊

**Comment by verynewabie** [comment]
没用过docker，重装了centos8stream，没毛病了
