### ISSUE TITLE
markdown 表格转图片样式

### ISSUE THREAD

**Issue by paul-sama** [kexue-z/nonebot-plugin-htmlrender#56]
markdown 表格转图片 怎么设置字体颜色，有例子吗。

**Comment by kexue-z** [comment]
直接使用HTML标签

<table>
  <tr style="color: red; font-weight: bold;">
    <th>语言</th>
    <th>特点</th>
  </tr>
  <tr>
    <td>Python</td>
    <td>易学易用，动态类型，适合快速开发，广泛应用于Web开发、数据分析等领域。</td>
  </tr>
  <tr>
    <td>Rust</td>
    <td>安全性高，内存管理严格，适合系统级编程和高性能应用开发，具备并发性和并行性。</td>
  </tr>
</table>

```html
<table>
  <tr style="color: red; font-weight: bold;">
    <th>语言</th>
    <th>特点</th>
  </tr>
  <tr>
    <td>Python</td>
    <td>易学易用，动态类型，适合快速开发，广泛应用于Web开发、数据分析等领域。</td>
  </tr>
  <tr>
    <td>Rust</td>
    <td>安全性高，内存管理严格，适合系统级编程和高性能应用开发，具备并发性和并行性。</td>
  </tr>
</table>
```

**Comment by paul-sama** [comment]
```
|---|---|
语言 |	特点
Python|	易学易用，动态类型，适合快速开发，广泛应用于 Web 开发、数据分析等领域。
Rust	|安全性高，内存管理严格，适合系统级编程和高性能应用开发，具备并发性和并行性。
```

上面的markdown转图片
就是表格了
有没有什么语法设置颜色或class的？

**Comment by kexue-z** [comment]
markdown 是可以直接用html的
