### ISSUE TITLE
htmlrender_proxy_host到底需要怎么配置

### ISSUE THREAD

**Issue by ikarosf** [kexue-z/nonebot-plugin-htmlrender#57]
我希望使用代理，config中也有该代理的配置项
但无论我在.env中填入
htmlrender_proxy_host=http://127.0.0.1:xxxx
还是
htmlrender_proxy_host={"server": “http://127.0.0.1:xxxx”}
都不起作用。
最终我修改browser.py中的代码，将
kwargs["proxy"] = proxy
改为
kwargs["proxy"] = {"server": proxy}
终于成功代理
关于此配置项如何设置能否说明一下

**Comment by kexue-z** [comment]
`v0.2.2`
