### ISSUE TITLE
请教一下html2img如何使用本地图片资源

### ISSUE THREAD

**Issue by mintianzan** [kexue-z/nonebot-plugin-htmlrender#58]
项目结构：
bot/
|-- data/
|xxx|-- template.html
|xxx|-- picture/
|xxxxxx |--picture.jpg
|-- plugins/
|xxx|-- nonebot_plugin_htmlrender/
|xxxxxx|--...
|xxx|-- ...
|-- bot.py

在html模板template文件中写了
    background-image: url(".picture/picture.jpg")

直接打开html文件可以正常加载图片
使用htmlrender的htmltoimg功能时可以加载除图片外的大部分其他内容，我参考了其他issue，将template_path参数设置为f"file://{data文件夹的绝对路径}",但仍然无法加载picture.jpg，请问应该如何正常使用呢

**Comment by kexue-z** [comment]
尽量使用绝对路径，或者在使用 `get_new_page` 方法中指定 `base_url`

例如:

await html_to_pic(html=html, base_url = ...):

> ***@***.***>
> 时间： 2023年10月18日 (周三) 13:30
> 主题： [kexue-z/nonebot-plugin-htmlrender] 请教一下html2img如何使用本地图片资源 (Issue #58)
> ***@***.***>
> ***@***.***>
> 项目结构：
> 
bot/
> 
|-- data/
> 
|   |-- template.html
> 
|   |-- picture/
> 
|       |--picture.jpg
> 
|-- plugins/
> 
|   |-- nonebot_plugin_htmlrender/
> 
|       |--...
> 
|   |-- ...
> 
|-- bot.py<http://bot.py>
> 在html模板template文件中写了
> 
background-image: url(".picture/picture.jpg")
> 直接打开html文件可以正常加载图片
> 
使用htmlrender的htmltoimg功能时可以加载除图片外的大部分其他内容，我参考了其他issue，将template_path参数设置为f"file://{data文件夹的绝对路径}",但仍然无法加载picture.jpg，请问应该如何正常使用呢

**Comment by mintianzan** [comment]
以上述目录为例，我在使用中指定
Template_path=str(Path("bot/data").absolute())
在使用await html_to_pic()时尝试了以下参数：
template_path=f"file://{Template_path}"
或
base_url=Template_path
或
base_url=f"file://{Template_path}"
均加载不出图片，请问在这个例子中正确的使用方式应该是什么呢

**Comment by kexue-z** [comment]
要 3 个 / 吧
file:///D:/git/dir

**Comment by mintianzan** [comment]
“file://D:/bot/data”
“file:///D:/bot/data”
将template_path和base_url分别以及同时设置为以上两种值都无法加载jpg图片

**Comment by kexue-z** [comment]
用这个吧 get_new_page

async def _html2pic(bot: Bot, event: MessageEvent):
    from pathlib import Path

    async with get_new_page(viewport={"width": 300, "height": 300}) as page:
        await page.goto(
            "file://" + (str(Path(__file__).parent / "html2pic.html")),
            wait_until="networkidle",
        )
        pic = await page.screenshot(full_page=True, path="./html2pic.png")

    await html2pic.finish(MessageSegment.image(pic))
