### ISSUE TITLE
[Feature] 允许配置 playwright 的channel参数

### ISSUE THREAD

**Issue by RF-Tar-Railt** [kexue-z/nonebot-plugin-htmlrender#59]
channel参数允许playwright直接使用现有浏览器而不是自己下载的浏览器内核，对于电脑上已经安装过Chrome或者Edge的用户能带来更好的体验

**Comment by kexue-z** [comment]
https://github.com/kexue-z/nonebot-plugin-htmlrender/commit/d82af0ea670d50793adbc9831402f1bc8541fb45

已发版
