### ISSUE TITLE
如何让playwright实例常驻后台

### ISSUE THREAD

**Issue by Yuelioi** [kexue-z/nonebot-plugin-htmlrender#60]
每次启动playwright感觉要消耗很长时间, 能否常驻后台呢

我想通过page获取一些网站上Dom上的图片, 所以使用get_new_page

```python
async def xx():
  async with get_new_page() as page:
      await page.goto('https://xxx')
      ...
```

但是指令结束后, 这个实例也就结束了, 我试了下和我直接使用async_playwright时间上没啥区别(启动耗时2 3秒感觉)

**Comment by kexue-z** [comment]
不关闭nb示例的话，应该就是常驻后台的

https://github.com/kexue-z/nonebot-plugin-htmlrender/blob/1b7bf8f1a0fda5d5fff71014969a5b5ad37c88f7/nonebot_plugin_htmlrender/__init__.py#L43-L46

https://github.com/kexue-z/nonebot-plugin-htmlrender/blob/1b7bf8f1a0fda5d5fff71014969a5b5ad37c88f7/nonebot_plugin_htmlrender/browser.py#L73-L81
