### ISSUE TITLE
[Feature] 添加 screenshot 的参数 omitBackground animations

### ISSUE THREAD

**Issue by yaowan233** [kexue-z/nonebot-plugin-htmlrender#67]
在渲染 echarts 图表时，截图时需要配置 omitBackground 为 False，否则会有一圈白边，希望可以提供参数进行配置

**Comment by kexue-z** [comment]
`**kwargs` 会传进page里面的，可以自己定

**Comment by yaowan233** [comment]
不是 page 的参数 我希望增加的参数在
https://github.com/kexue-z/nonebot-plugin-htmlrender/blob/9d9ba5f3762107b3c18370709847b07c474354e0/nonebot_plugin_htmlrender/data_source.py#L199-L203
在 page 里面 没办法改 omitBackground 吧
