### ISSUE TITLE
自适应模版长宽

### ISSUE THREAD

**Issue by KiKi-XC** [kexue-z/nonebot-plugin-htmlrender#74]
希望在后续更新中添加template_to_pic的自适应功能，而不是使用viewport自定义长宽

**Comment by kexue-z** [comment]
没理解什么意思

目前截图就是按照 playwright 的截图来的

设置了 viewpoint 宽度后，加上 fullpage 参数 就会生成长截图（默认）

并且代码里面把高度设置很低，也不会影响长截图的效果

如果你的内容高度小于默认的高度，才会出现截图的空白

**Comment by Cathgao** [comment]
> 没理解什么意思
> 
> 目前截图就是按照 playwright 的截图来的
> 
> 设置了 viewpoint 宽度后，加上 fullpage 参数 就会生成长截图（默认）
> 
> 并且代码里面把高度设置很低，也不会影响长截图的效果
> 
> 如果你的内容高度小于默认的高度，才会出现截图的空白

意思是可以自适应宽度，而不是手动调整。我现在也是有一些宽的表格显示不全

<img width="412" height="426" alt="Image" src="https://github.com/user-attachments/assets/bf41dbc2-26e7-43d7-b43d-b7f7d2f8626e" />
