### ISSUE TITLE
[建议]希望能够连接远程浏览器)

### ISSUE THREAD

**Issue by FLY1919** [kexue-z/nonebot-plugin-htmlrender#78]
[pyppeteer2](https://pypi.org/project/pyppeteer2/)
话说，能不能通过这个库连接其他设备的浏览器渲染()
~~如果能多设备负载均衡渲染就好了~~
希望主播能采纳(()

**Comment by kexue-z** [comment]
playwright自带有连接其他浏览器
> ***@***.***>
> 时间： 2024年10月20日 (周日) 下午5:17
> 主题： [kexue-z/nonebot-plugin-htmlrender] [建议]希望能够连接远程浏览器) (Issue #78)
> ***@***.***>
> ***@***.***>
> pyppeteer2<https://pypi.org/project/pyppeteer2/>
> 
话说，能不能通过这个库连接其他设备的浏览器渲染()
> 如果能多设备负载均衡渲染就好了
> 
希望主播能采纳(()

**Comment by FLY1919** [comment]
真的吗？那太感谢了(((((((()
抱歉，打扰了)

**Comment by FLY1919** [comment]
远程连接其他设备也有吗(((()
